---
title: Hanne Oberman 
subtitle: Talks, lectures, and presentations
email-obfuscation: javascript
css: styles.css
website: 
  favicon: logo.png
format:
  html:
    theme: 
      light: [lux, theme-light.scss]
---

<center>

<link rel=stylesheet href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
<link rel=stylesheet href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
<a rel="me" href="https://mastodon.social/@oberman"></a>

<a href=https://hanneoberman.github.io/ class="fa fa-home"></a>
<a href=https://www.uu.nl/staff/HIOberman class="fa fa-building"></a>
<a href=mailto:h.i.oberman@uu.nl class="fa fa-envelope"></a>
<a href=https://orcid.org/0000-0003-3276-2141 class="ai ai-orcid"></a>
<a href=https://github.com/hanneoberman/ class="fa-brands fa-github"></a>
<a href=https://www.linkedin.com/in/hanneoberman/ class="fa-brands fa-linkedin"></a>
<a href=https://mastodon.social/@oberman class="fa-brands fa-mastodon"></a>
<a href=https://twitter.com/hioberman class="fa-brands fa-twitter"></a>
<a href=https://bsky.app/profile/oberman.bsky.social class="fa-brands fa-bluesky"></a>

</center>

## 2025

- Presentation ISI 2025, Utrecht, *Data visualization for incomplete datasets in `R`*. Slides available [here](https://hanneoberman.github.io/presentations/2025/ISI/Data_visualization_for_incomplete_datasets_in_R.html), materials available [here](https://github.com/hanneoberman/presentations/tree/main/2025/ISI).
- Presentation ESRA 2025, Utrecht, *Computational Reproducibility in Statistics*. Slides available [here](https://hanneoberman.github.io/presentations/2025/ESRA/Computational_Reproducibility_in_Statistics.html), materials available [here](https://github.com/hanneoberman/presentations/tree/main/2025/ESRA).
- Presentation ESRA 2025, Utrecht, *Data visualization for incomplete datasets in `R`*. Slides available [here](https://hanneoberman.github.io/presentations/2025/ESRA/Data_visualization_for_incomplete_datasets_in_R.html), materials available [here](https://github.com/hanneoberman/presentations/tree/main/2025/ESRA).
- Poster METASCIENCE 2025, University College London, *What is ‘Open Science’? Operationalisation of Open Science in Survey Research*. Poster PDF available [here](https://hanneoberman.github.io/presentations/2025/METASCIENCE/Metascience.pdf).
- Lecture Applied Data Analysis and Visualization, Utrecht University,  *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2025/ADAV/shiny.pdf), materials available [here](https://github.com/hanneoberman/presentations/2025/ADAV).

## 2024

- Poster NLRN Symposium 2024, UMC Groningen, *Teaching Reproducibility to Research Master's Students*. Poster available [here](https://hanneoberman.github.io/presentations/2024/NLRN/poster.pdf).
- Lecture MSBBSS, Utrecht University, *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2024/markup/lecture.pdf).
- Lecture SHP03, Utrecht University, *Logistic regression*. Slides available [here](https://hanneoberman.github.io/presentations/2024/SHP03/logistic.html) and [static as PDF](https://hanneoberman.github.io/presentations/2024/SHP03/logistic.pdf).
- Tutorial useR! 2024, Salzburg, *Missing data exploration, imputation, and evaluation*. Slides available [here](https://hanneoberman.github.io/presentations/2024/useR/slides.html).
- Lecture Applied Data Analysis and Visualization, Utrecht University,  *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2024/ADAV/shiny.pdf).
- Tutorial at EMLAR, Utrecht, *Open Science using the statistical package JASP*. Slides available [here](https://hanneoberman.github.io/presentations/2024/EMLAR/OpenYourScience.pdf). Download all materials from [here](https://hanneoberman.github.io/presentations/2024/EMLAR/EMLAR.zip).
- Presentation Annual Meeting of the Netherlands Society for Statistics and Operations Research (VVSOR), Utrecht, *Data visualization for incomplete datasets in R*. Slides available [here](https://hanneoberman.github.io/presentations/2024/VVSOR/Data_visualization_for_incomplete_datasets_in_R.html)
- Presentation Multilevel Conference, Utrecht, *Imputation of Incomplete Multilevel Data with R*. Slides available [here](https://hanneoberman.github.io/presentations/2024/Multilevel/ImputationOfIncompleteMultilevelDataWithR.html).

## 2023

- Lecture Markup Languages and Reproducible Programming in Statistics, Utrecht University,  *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2023/MLaRPiS/lecture.pdf).
- Lecture summer school Statistical Programming with R, Utrecht University,  *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2023/R_summer_school/lecture.pdf).
- Presentation EAM2023 Conference, Gent, *Towards a standardized evaluation of imputation methodology: Potential pitfalls in simulation studies and a proposed course of action*. Slides available [here](https://hanneoberman.github.io/presentations/2023/EAM/presentation.html).

## 2022

- Lecture Applied Data Analysis and Visualization, Utrecht University, *Building interactive web apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2022/shiny/Building interactive web apps.pdf).

## 2021

- Guest lecture MSc Methodology and Statistics, Utrecht University, *Some Shiny Stuff: building (web)apps with the `R` package `shiny`*. Slides available [here](https://hanneoberman.github.io/presentations/2021/shiny/static/shiny_guest_lecture_static.html).
