---
title: "MSBBSS04: Statistical programming in R"
subtitle: "Lab: Debugging R"
format: pdf
---

*Work preferably in pairs and perform all commands in this practical using RStudio or the built-in R editor. Put the answers to the questions as comment in the script and add comments to your script to explain what you do, using the hash (#) sign. At the end of this document you will find instructions about how and when to hand in your work.*

<!-- Lab: Debugging R -->

## Exercises

Download the zip folder with this week's exercises. The folder contains three subfolders with exercises:

* `01_exercise` practice debugging your own code

* `02_exercise` practice debugging your own code with RStudio IDE features

* `03_exercise` (*optional!*) practice debugging others' code


For each exercise, you can 'choose your own adventure' by selecting the R script with more or with less hints:

* `0X_debugging_spartan.R` (directions to explore without suggested code)

* `0X_debugging_comfy.R` (directions to explore with suggested code)

Your homework is to hand in a version of exercises `01` and `02`. 
This may be either the `spartan` or `comfy` version of each exercise.
The third exercise does not need to be handed in.

Next week, the solutions will be added:

* `0X_debugging_solution.R` (directions to explore with code solutions)


## Hint

Remember to restart R as indicated. In the RStudio IDE:

* Session -> Restart R, or

* Ctrl + Shift + F10 (Windows),

* Cmd + Shift + 0 / Cmd + Shift + F10 (Mac)

# Instructions for handing in your work

- Put your answers to the questions to the R script and mark the text as comment by using the hashtag (#) sign. Add comments to your script explaining what you are doing.
- Save the script file. Name the file as follows: YourNameLabXXX.R (where XXX is the topic of the week or the week number).
- Hand in the .R or .qmd file at least one day before the next class session. Do this via the learning environment.